/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace MonForm {
  export type FormStruct = {
    owner: AddressLike;
    metadataId: string;
    ownerPubKey: string;
    createdAt: BigNumberish;
  };

  export type FormStructOutput = [
    owner: string,
    metadataId: string,
    ownerPubKey: string,
    createdAt: bigint
  ] & {
    owner: string;
    metadataId: string;
    ownerPubKey: string;
    createdAt: bigint;
  };
}

export interface MonFormInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createForm"
      | "formCount"
      | "forms"
      | "getForm"
      | "getSubmission"
      | "getSubmitters"
      | "hasSubmitted"
      | "submitResponse"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "FormCreated" | "ResponseSubmitted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "createForm",
    values: [string, string]
  ): string;
  encodeFunctionData(functionFragment: "formCount", values?: undefined): string;
  encodeFunctionData(functionFragment: "forms", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "getForm",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSubmission",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSubmitters",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasSubmitted",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitResponse",
    values: [BigNumberish, string]
  ): string;

  decodeFunctionResult(functionFragment: "createForm", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "formCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "forms", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getForm", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getSubmission",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSubmitters",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasSubmitted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitResponse",
    data: BytesLike
  ): Result;
}

export namespace FormCreatedEvent {
  export type InputTuple = [
    formId: BigNumberish,
    owner: AddressLike,
    metadataId: string
  ];
  export type OutputTuple = [formId: bigint, owner: string, metadataId: string];
  export interface OutputObject {
    formId: bigint;
    owner: string;
    metadataId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ResponseSubmittedEvent {
  export type InputTuple = [
    formId: BigNumberish,
    submitter: AddressLike,
    ipfsCID: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    formId: bigint,
    submitter: string,
    ipfsCID: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    formId: bigint;
    submitter: string;
    ipfsCID: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MonForm extends BaseContract {
  connect(runner?: ContractRunner | null): MonForm;
  waitForDeployment(): Promise<this>;

  interface: MonFormInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createForm: TypedContractMethod<
    [metadataId: string, ownerPubKey: string],
    [bigint],
    "nonpayable"
  >;

  formCount: TypedContractMethod<[], [bigint], "view">;

  forms: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, bigint] & {
        owner: string;
        metadataId: string;
        ownerPubKey: string;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  getForm: TypedContractMethod<
    [formId: BigNumberish],
    [MonForm.FormStructOutput],
    "view"
  >;

  getSubmission: TypedContractMethod<
    [formId: BigNumberish, submitter: AddressLike],
    [[string, bigint] & { ipfsCID: string; timestamp: bigint }],
    "view"
  >;

  getSubmitters: TypedContractMethod<
    [formId: BigNumberish],
    [string[]],
    "view"
  >;

  hasSubmitted: TypedContractMethod<
    [formId: BigNumberish, submitter: AddressLike],
    [boolean],
    "view"
  >;

  submitResponse: TypedContractMethod<
    [formId: BigNumberish, ipfsCID: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createForm"
  ): TypedContractMethod<
    [metadataId: string, ownerPubKey: string],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "formCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "forms"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, bigint] & {
        owner: string;
        metadataId: string;
        ownerPubKey: string;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getForm"
  ): TypedContractMethod<
    [formId: BigNumberish],
    [MonForm.FormStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSubmission"
  ): TypedContractMethod<
    [formId: BigNumberish, submitter: AddressLike],
    [[string, bigint] & { ipfsCID: string; timestamp: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSubmitters"
  ): TypedContractMethod<[formId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "hasSubmitted"
  ): TypedContractMethod<
    [formId: BigNumberish, submitter: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "submitResponse"
  ): TypedContractMethod<
    [formId: BigNumberish, ipfsCID: string],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "FormCreated"
  ): TypedContractEvent<
    FormCreatedEvent.InputTuple,
    FormCreatedEvent.OutputTuple,
    FormCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ResponseSubmitted"
  ): TypedContractEvent<
    ResponseSubmittedEvent.InputTuple,
    ResponseSubmittedEvent.OutputTuple,
    ResponseSubmittedEvent.OutputObject
  >;

  filters: {
    "FormCreated(uint256,address,string)": TypedContractEvent<
      FormCreatedEvent.InputTuple,
      FormCreatedEvent.OutputTuple,
      FormCreatedEvent.OutputObject
    >;
    FormCreated: TypedContractEvent<
      FormCreatedEvent.InputTuple,
      FormCreatedEvent.OutputTuple,
      FormCreatedEvent.OutputObject
    >;

    "ResponseSubmitted(uint256,address,string,uint256)": TypedContractEvent<
      ResponseSubmittedEvent.InputTuple,
      ResponseSubmittedEvent.OutputTuple,
      ResponseSubmittedEvent.OutputObject
    >;
    ResponseSubmitted: TypedContractEvent<
      ResponseSubmittedEvent.InputTuple,
      ResponseSubmittedEvent.OutputTuple,
      ResponseSubmittedEvent.OutputObject
    >;
  };
}
